version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app-network

  db:
    image: nouchka/sqlite3  # This can be removed as SQLite is embedded in the Django container, no need to spin a separate db container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
