version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "sleep 6 && npm start"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    #environment:
      #- DATABASE_URL=postgres://user:password@database:5432/db
    working_dir: /app
    command: bash -c "sleep 3 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py create_default_tags && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:13
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
